### PR TITLE
i18nify login page

### PR DESCRIPTION
**Pull request by 2sh**
I thought the front page looked a a bit cluttered so I've made the gen and for buttons change the language.
For switching the change log language I've added v-show="$i18n.locale == 'XX'" to the change log sections as they'll be going into that external file.

### CODE REVIEW

**Comment by iccanobif** [comment]
oh great idea!

**Comment by 2sh** [comment]
Some more notes:
- Just realised it's a master commit behind so one of the change log messages is missing.
- I messed with the CSS margin and padding a bit but wasn't quite sure in the end. Could probably have left it.
- Moved the area selection to the top because I thought it's the first thing you do on the original too and it changes the language for the rest of the form. Felt better there somehow.

**Comment by iccanobif** [comment]
> Moved the area selection to the top because I thought it's the first thing you do on the original too and it changes the language for the rest of the form. Felt better there somehow.

Makes sense. Regarding the login page's usability, I was also thinking that it would be nice to remember the username, area and character selection in the local storage. And even better would be remembering a different username and character per area (like the original, and I also personally tend to use giko on _for and boon on _gen, maybe other people would also find it convenient).

If it makes sense for you too, i'll add a new issue

**Comment by 2sh** [comment]
Yes makes sense. Had been thinking similarly.

**Comment by 2sh** [comment]
I've updated the change log

**Pull request merged**
