### PR TITLE
Feat: add current streamers api

### PR DESCRIPTION
**Pull request by TakigiTakamura**
add current streamers api
this api is for no.3 in https://github.com/iccanobif/gikopoi2/issues/193 .
> notify of users current streamers list in twitter and discord.

primitive implementation is for avoiding effects for existing codes.
it is planned twitter bot and others are placed at gss.

### CODE REVIEW

**Comment by 2sh** [comment]
Sorry but I don't like this searching through the lang.js file with splits and regex. It will just create problems in the future.

**Comment by TakigiTakamura** [comment]
@2sh 
thanks for your reviewing.
that's exactly right.
i removed primitive codes and change notification design.

**Comment by iccanobif** [comment]
what's gss?

**Comment by TakigiTakamura** [comment]
@iccanobif 
gss is google spreadsheet (with google apps script).
it can hosts apps for free.

**Comment by iccanobif** [comment]
Interesting, I didn't know that was possible.
Merging, so this change will be ready on the website on the next release

**Pull request merged**
